version: "3"
services:
  docker_mysql:
    image: mysql:debian
    container_name: mysql_container 
    ports:
      - "3310:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123m
      MYSQL_DATABASE: segundaBase
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
